kind: Service
apiVersion: v1
metadata:
  name: vrekon-backend-service
spec:
  type: NodePort
  selector:
    app: vrekon-backend
  ports:
  - protocol: TCP
    port: 4200
    nodePort: 30200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrekon-backend-deployment
  labels:
    app: vrekon-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vrekon-backend
      track: stable
  template:
    metadata:
      labels:
        app: vrekon-backend
        track: stable
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 4200
        livenessProbe:
          httpGet:
            path: /
            port: 4200
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
